package com.localandro.gemma4e2b.domain.model

import java.util.UUID

/**
 * Represents a single message in the chat conversation.
 *
 * @param id Unique identifier for the message.
 * @param role Who authored the message (user, model, or system).
 * @param content Textual content of the message.
 * @param timestamp Unix epoch millis when the message was created.
 */
data class Message(
    val id: String = UUID.randomUUID().toString(),
    val role: MessageRole,
    val content: String,
    val timestamp: Long = System.currentTimeMillis()
)

/** Identifies the author of a [Message]. */
enum class MessageRole {
    /** Message authored by the human user. */
    USER,
    /** Message generated by the Gemma 4 model. */
    MODEL,
    /** System-level message (e.g. initialization status). */
    SYSTEM,
    /** A tool invocation emitted by the model via <|tool_call|>. */
    TOOL_CALL,
    /** The result of a tool execution injected back into context. */
    TOOL_RESULT
}
